# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='', max_length=200, verbose_name='教师提醒'),
        ),
    ]
