# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_youneed_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teahcher_tell',
            field=models.CharField(max_length=100, null=True, verbose_name='学到什么'),
        ),
    ]
